version: '3'

services:
  psql:
    image: 'postgres:13.3'
    container_name: 'postgres-logics-school'
    ports:
      - "5432:5432"
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bot
    networks:
      - application-network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Logics-school
    ports:
      - "8080:8080"
    restart: "no"
    depends_on:
      - psql
    environment:
      RDS_HOSTNAME: psql
      RDS_PORT: 5432
      RDS_DB_NAME: bot
      RDS_USERNAME: postgres
      RDS_PASSWORD: postgres
    networks:
      - application-network

volumes:
  postgres-data: {}

networks:
  application-network: {}