spring:
  flyway:
    locations: classpath:db/migration
    schemas: bot
    enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    database: postgresql
  datasource:
#    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5432}/${RDS_DB_NAME:bot}?currentSchema=bot
    url: jdbc:postgresql://${RDS_HOSTNAME:45.8.251.166}:${RDS_PORT:5432}/${RDS_DB_NAME:postgres}?currentSchema=bot
#    url: jdbc:postgresql://${RDS_HOSTNAME:host.docker.internal:${RDS_PORT:5432}/${RDS_DB_NAME:bot}?currentSchema=bot
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    pool-size: 30

  kafka:
#    bootstrap-servers: localhost:9092
    bootstrap-servers: 81.163.31.123:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false
    topicName: top1

bot:
  name: LogicaScol
  token: 5594650440:AAFbqVQvSmHwL2SCtDrkw5gQePfMRJCWahw
  owner: 1

cron:
#  scheduler: 0 * * * * ?
  scheduler: 0 */5 * * * *
  job:
    statisticEveryDay: 0 59 20 * * *
    statusQr: 13 */5 * * * *
    delete_qr: 0 59 20 * * *
#    replica: 13 13 * * * *
    replica: 13 * * * * *

management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

server:
  port: 8888