spring:
  flyway:
    locations: classpath:db/migration
    schemas: bot
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: postgresql
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5432}/${RDS_DB_NAME:bot}?currentSchema=bot
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

bot:
  name: LogicaScol
  token: 5594650440:AAFbqVQvSmHwL2SCtDrkw5gQePfMRJCWahw
  owner: 1

cron:
#  scheduler: 0 * * * * ?
  scheduler: 0 */5 * * * *

